language: php
git:
  depth: 1
php:
  - '7.1'
install:
  - travis_retry composer install --no-interaction
  - travis_retry composer require --no-interaction --dev satooshi/php-coveralls
script:
  - composer test-coverage
  - composer test
after_script:
  - composer upload-coverage
branches:
  only: master